# Generated by Django 3.1.13 on 2021-09-13 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WallRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rank_nmubers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('voters', models.PositiveIntegerField(default=0)),
                ('wall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wall_rank', to='wall.userwall')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VotedRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rank', models.PositiveSmallIntegerField(choices=[(10, 'incredible'), (9, 'brilliant'), (8, 'fantastic'), (7, 'very good'), (6, 'good'), (5, 'average'), (4, 'below average'), (3, 'bad'), (2, 'very_bad'), (1, 'awful')])),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_voter', to=settings.AUTH_USER_MODEL)),
                ('wall_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='ranks.wallrank')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
