# Generated by Django 3.1.13 on 2021-09-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallrank',
            name='rank_nmubers',
        ),
        migrations.AddField(
            model_name='wallrank',
            name='rank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votedrank',
            name='wall_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_rank', to='ranks.wallrank'),
        ),
    ]
