# Generated by Django 3.1.13 on 2021-09-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0002_auto_20210921_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedrank',
            name='wall_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votedrank', to='ranks.wallrank'),
        ),
    ]
