# Generated by Django 3.1.13 on 2021-09-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredit',
            old_name='Credit',
            new_name='credit',
        ),
    ]
