# Generated by Django 3.1.13 on 2021-09-27 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0002_auto_20210913_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('credit_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_receiver', to=settings.AUTH_USER_MODEL)),
                ('credit_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
