# Generated by Django 3.1.13 on 2021-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20210921_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='type',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
